const productData = {
  statusCode: 200,
  message: "Success",
  success: true,
  data: {
    products: [
      {
        _id: "1",
        name: "Nike Air Zoom Pegasus 39",
        description: "Top-quality running shoes with a sleek design.",
        price: 7999,
        originalPrice: 9999,
        discount: "20% off",
        category: "Footwear",
        brand: "Nike",
        stock: 8,
        size: ["7", "8", "9", "10"], // Added sizes
        color: ["Black", "White", "Blue"], // Available colors
        images: [
          {
            url: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Nike Shoes",
            _id: "img1-nike",
          },
        ],
        rating: 4.5,
        isFeatured: true,
        reviews: [],
        discountValue: 2000,
      },
      {
        _id: "2",
        name: "Adidas Ultraboost 21",
        description: "Comfortable sneakers for daily running and sports.",
        price: 8999,
        originalPrice: 11999,
        discount: "25% off",
        category: "Footwear",
        brand: "Adidas",
        stock: 5,
        size: ["7", "8", "9", "11"],
        color: ["White", "Gray"],
        images: [
          {
            url: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Adidas Shoes",
            _id: "img2-adidas",
          },
        ],
        rating: 4.8,
        isFeatured: false,
        reviews: [],
        discountValue: 3000,
      },
      {
        _id: "6",
        name: "Sony WH-1000XM4 Headphones",
        description: "Noise-canceling wireless headphones for audiophiles.",
        price: 19999,
        originalPrice: 24999,
        discount: "20% off",
        category: "Electronics",
        brand: "Sony",
        stock: 6,
        color: ["Black", "Silver"], // Added color for electronics
        warranty: "1 Year", // Added warranty field
        batteryLife: "30 hours", // Additional field
        images: [
          {
            url: "https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Sony Headphones",
            _id: "img6-sony",
          },
        ],
        rating: 4.9,
        isFeatured: true,
        reviews: [],
        discountValue: 5000,
      },
      {
        _id: "7",
        name: "Apple MacBook Pro M1",
        description: "Powerful laptop with M1 chip and Retina display.",
        price: 99999,
        originalPrice: 129999,
        discount: "23% off",
        category: "Electronics",
        brand: "Apple",
        stock: 3,
        color: ["Silver", "Space Gray"], // Electronics colors
        processor: "Apple M1",
        ram: "16GB", // Added hardware specs
        storage: "512GB SSD",
        warranty: "1 Year",
        images: [
          {
            url: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Apple MacBook",
            _id: "img7-macbook",
          },
        ],
        rating: 5.0,
        isFeatured: true,
        reviews: [],
        discountValue: 30000,
      },
      {
        _id: "8",
        name: "Samsung Galaxy Watch 5",
        description: "Smartwatch with health tracking and sleek design.",
        price: 14999,
        originalPrice: 19999,
        discount: "25% off",
        category: "Wearables",
        brand: "Samsung",
        stock: 10,
        color: ["Black", "Silver"],
        batteryLife: "40 hours",
        warranty: "1 Year",
        features: ["Heart Rate Monitor", "Sleep Tracking", "GPS"],
        images: [
          {
            url: "https://images.pexels.com/photos/416404/pexels-photo-416404.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Samsung Watch",
            _id: "img8-watch",
          },
        ],
        rating: 4.7,
        isFeatured: false,
        reviews: [],
        discountValue: 5000,
      },
      {
        _id: "4",
        name: "Reebok Classic Leather",
        description: "Vintage classic shoes with modern comfort.",
        price: 4999,
        originalPrice: 6999,
        discount: "30% off",
        category: "Footwear",
        brand: "Reebok",
        stock: 2,
        size: ["8", "9", "10"],
        color: ["Black", "Brown"],
        images: [
          {
            url: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Reebok Classic",
            _id: "img4-reebok",
          },
        ],
        rating: 4.1,
        isFeatured: false,
        reviews: [],
        discountValue: 2000,
      },
      {
        _id: "10",
        name: "Canon EOS R6 Camera",
        description: "Full-frame mirrorless camera for professionals.",
        price: 199999,
        originalPrice: 229999,
        discount: "13% off",
        category: "Cameras",
        brand: "Canon",
        stock: 4,
        color: ["Black"],
        warranty: "2 Years",
        resolution: "20.1 MP",
        features: ["4K Video Recording", "Fast Autofocus", "WiFi Enabled"],
        images: [
          {
            url: "https://images.pexels.com/photos/177815/pexels-photo-177815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Canon Camera",
            _id: "img10-canon",
          },
        ],
        rating: 5.0,
        isFeatured: true,
        reviews: [],
        discountValue: 30000,
      },

      {
        _id: "11",
        name: "Adidas Ultraboost 21",
        description: "Comfortable sneakers for daily running and sports.",
        price: 8999,
        originalPrice: 11999,
        discount: "25% off",
        category: "Footwear",
        brand: "Adidas",
        stock: 5,
        size: ["7", "8", "9", "11"],
        color: ["White", "Gray"],
        images: [
          {
            url: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Adidas Shoes",
            _id: "img2-adidas",
          },
        ],
        rating: 4.8,
        isFeatured: false,
        reviews: [],
        discountValue: 3000,
      },
      {
        _id: "12",
        name: "Sony WH-1000XM4 Headphones",
        description: "Noise-canceling wireless headphones for audiophiles.",
        price: 19999,
        originalPrice: 24999,
        discount: "20% off",
        category: "Electronics",
        brand: "Sony",
        stock: 6,
        color: ["Black", "Silver"], // Added color for electronics
        warranty: "1 Year", // Added warranty field
        batteryLife: "30 hours", // Additional field
        images: [
          {
            url: "https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Sony Headphones",
            _id: "img6-sony",
          },
        ],
        rating: 4.9,
        isFeatured: true,
        reviews: [],
        discountValue: 5000,
      },
      {
        _id: "13",
        name: "Apple MacBook Pro M1",
        description: "Powerful laptop with M1 chip and Retina display.",
        price: 99999,
        originalPrice: 129999,
        discount: "23% off",
        category: "Electronics",
        brand: "Apple",
        stock: 3,
        color: ["Silver", "Space Gray"], // Electronics colors
        processor: "Apple M1",
        ram: "16GB", // Added hardware specs
        storage: "512GB SSD",
        warranty: "1 Year",
        images: [
          {
            url: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Apple MacBook",
            _id: "img7-macbook",
          },
        ],
        rating: 5.0,
        isFeatured: true,
        reviews: [],
        discountValue: 30000,
      },
      {
        _id: "14",
        name: "Samsung Galaxy Watch 5",
        description: "Smartwatch with health tracking and sleek design.",
        price: 14999,
        originalPrice: 19999,
        discount: "25% off",
        category: "Wearables",
        brand: "Samsung",
        stock: 10,
        color: ["Black", "Silver"],
        batteryLife: "40 hours",
        warranty: "1 Year",
        features: ["Heart Rate Monitor", "Sleep Tracking", "GPS"],
        images: [
          {
            url: "https://images.pexels.com/photos/416404/pexels-photo-416404.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Samsung Watch",
            _id: "img8-watch",
          },
        ],
        rating: 4.7,
        isFeatured: false,
        reviews: [],
        discountValue: 5000,
      },
      {
        _id: "15",
        name: "Reebok Classic Leather",
        description: "Vintage classic shoes with modern comfort.",
        price: 4999,
        originalPrice: 6999,
        discount: "30% off",
        category: "Footwear",
        brand: "Reebok",
        stock: 2,
        size: ["8", "9", "10"],
        color: ["Black", "Brown"],
        images: [
          {
            url: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Reebok Classic",
            _id: "img4-reebok",
          },
        ],
        rating: 4.1,
        isFeatured: false,
        reviews: [],
        discountValue: 2000,
      },
      {
        _id: "16",
        name: "Canon EOS R6 Camera",
        description: "Full-frame mirrorless camera for professionals.",
        price: 199999,
        originalPrice: 229999,
        discount: "13% off",
        category: "Cameras",
        brand: "Canon",
        stock: 4,
        color: ["Black"],
        warranty: "2 Years",
        resolution: "20.1 MP",
        features: ["4K Video Recording", "Fast Autofocus", "WiFi Enabled"],
        images: [
          {
            url: "https://images.pexels.com/photos/177815/pexels-photo-177815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
            alt: "Canon Camera",
            _id: "img10-canon",
          },
        ],
        rating: 5.0,
        isFeatured: true,
        reviews: [],
        discountValue: 30000,
      },
    ],
    totalProducts: 10,
    totalPages: 1,
    currentPage: 1,
    facets: {
      categories: ["Footwear", "Electronics", "Wearables", "Cameras"],
      brands: [
        "Nike",
        "Adidas",
        "Puma",
        "Reebok",
        "Apple",
        "Sony",
        "Samsung",
        "Canon",
      ],
      priceRange: {
        min: 4999,
        max: 199999,
      },
    },
  },
};

export default productData;
